name = "Theseus"
uuid = "047ba4bf-f634-41ae-9160-c87fc483a8de"
version = "1.0.0-DEV"
authors = ["adam-burke", "keith-j-lee"]

[deps]
ADTypes = "47edcb42-4c32-4615-8424-f2b9edc5f35b"
DifferentiationInterface = "a0c0ee7d-e4b9-4e03-894e-1c5f64a51d63"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
LDLFactorizations = "40e66cde-538c-5869-a4ad-c39174c6795b"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Mooncake = "da2b9cff-9c12-43a0-ae48-6db2b0edb7d6"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
TimerOutputs = "a759f4b9-e2f1-59dc-863e-4aeb61b1ea8f"

[compat]
ADTypes = "1.21.0"
DifferentiationInterface = "0.7.14"
HTTP = "1.10.19"
JSON3 = "1.14.3"
LDLFactorizations = "0.10.1"
LinearAlgebra = "1.11.0"
Mooncake = "0.4.201"
Optim = "1.13.2"
SparseArrays = "1.11.0"
TimerOutputs = "0.5"
julia = "1.11"

[extras]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "BenchmarkTools"]
