name = "Theseus"
uuid = "047ba4bf-f634-41ae-9160-c87fc483a8de"
version = "1.0.0-DEV"
authors = ["adam-burke", "keith-j-lee"]

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
DifferentiationInterface = "a0c0ee7d-e4b9-4e03-894e-1c5f64a51d63"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
LDLFactorizations = "40e66cde-538c-5869-a4ad-c39174c6795b"
LineSearches = "d3d80556-e9d4-5f37-9878-2ab0fcc64255"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LinearSolve = "7ed4a6bd-45f5-4d41-b270-4a48e9bafcae"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
MKL = "33e6dc65-8f57-5167-99aa-e5a354878fb2"
Mooncake = "da2b9cff-9c12-43a0-ae48-6db2b0edb7d6"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
SparseDiffTools = "47a9eef4-7e08-11e9-0b38-333d64bd3804"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
BenchmarkTools = "1.6.3"
ChainRulesCore = "1.26.0"
DifferentiationInterface = "0.7.14"
HTTP = "1.10.19"
JSON3 = "1.14.3"
LDLFactorizations = "0.10.1"
LineSearches = "7.4.0"
LinearAlgebra = "1.11.0"
LinearSolve = "3.26.0"
Logging = "1.11.0"
MKL = "0.9.0"
Mooncake = "0.4.201"
Optim = "1.13.2"
Revise = "3.10.0"
SparseArrays = "1.11.0"
SparseDiffTools = "2.26.0"
Statistics = "1.11.1"
julia = "1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
